// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: serviciosCanciones.proto

package serviciosCanciones

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genero) Reset() {
	*x = Genero{}
	mi := &file_serviciosCanciones_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genero) ProtoMessage() {}

func (x *Genero) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCanciones_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genero.ProtoReflect.Descriptor instead.
func (*Genero) Descriptor() ([]byte, []int) {
	return file_serviciosCanciones_proto_rawDescGZIP(), []int{0}
}

func (x *Genero) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genero) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type Cancion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Artista       string                 `protobuf:"bytes,3,opt,name=artista,proto3" json:"artista,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	Anio          int32                  `protobuf:"varint,5,opt,name=anio,proto3" json:"anio,omitempty"`
	Duracion      string                 `protobuf:"bytes,6,opt,name=duracion,proto3" json:"duracion,omitempty"`
	Genero        *Genero                `protobuf:"bytes,7,opt,name=genero,proto3" json:"genero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancion) Reset() {
	*x = Cancion{}
	mi := &file_serviciosCanciones_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancion) ProtoMessage() {}

func (x *Cancion) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCanciones_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancion.ProtoReflect.Descriptor instead.
func (*Cancion) Descriptor() ([]byte, []int) {
	return file_serviciosCanciones_proto_rawDescGZIP(), []int{1}
}

func (x *Cancion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cancion) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Cancion) GetArtista() string {
	if x != nil {
		return x.Artista
	}
	return ""
}

func (x *Cancion) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Cancion) GetAnio() int32 {
	if x != nil {
		return x.Anio
	}
	return 0
}

func (x *Cancion) GetDuracion() string {
	if x != nil {
		return x.Duracion
	}
	return ""
}

func (x *Cancion) GetGenero() *Genero {
	if x != nil {
		return x.Genero
	}
	return nil
}

type ListaGeneros struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generos       []*Genero              `protobuf:"bytes,1,rep,name=generos,proto3" json:"generos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaGeneros) Reset() {
	*x = ListaGeneros{}
	mi := &file_serviciosCanciones_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaGeneros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaGeneros) ProtoMessage() {}

func (x *ListaGeneros) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCanciones_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaGeneros.ProtoReflect.Descriptor instead.
func (*ListaGeneros) Descriptor() ([]byte, []int) {
	return file_serviciosCanciones_proto_rawDescGZIP(), []int{2}
}

func (x *ListaGeneros) GetGeneros() []*Genero {
	if x != nil {
		return x.Generos
	}
	return nil
}

type GeneroId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneroId) Reset() {
	*x = GeneroId{}
	mi := &file_serviciosCanciones_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneroId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneroId) ProtoMessage() {}

func (x *GeneroId) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCanciones_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneroId.ProtoReflect.Descriptor instead.
func (*GeneroId) Descriptor() ([]byte, []int) {
	return file_serviciosCanciones_proto_rawDescGZIP(), []int{3}
}

func (x *GeneroId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListaCanciones struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canciones     []*Cancion             `protobuf:"bytes,1,rep,name=canciones,proto3" json:"canciones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaCanciones) Reset() {
	*x = ListaCanciones{}
	mi := &file_serviciosCanciones_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaCanciones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaCanciones) ProtoMessage() {}

func (x *ListaCanciones) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCanciones_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaCanciones.ProtoReflect.Descriptor instead.
func (*ListaCanciones) Descriptor() ([]byte, []int) {
	return file_serviciosCanciones_proto_rawDescGZIP(), []int{4}
}

func (x *ListaCanciones) GetCanciones() []*Cancion {
	if x != nil {
		return x.Canciones
	}
	return nil
}

type CancionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancionId) Reset() {
	*x = CancionId{}
	mi := &file_serviciosCanciones_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancionId) ProtoMessage() {}

func (x *CancionId) ProtoReflect() protoreflect.Message {
	mi := &file_serviciosCanciones_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancionId.ProtoReflect.Descriptor instead.
func (*CancionId) Descriptor() ([]byte, []int) {
	return file_serviciosCanciones_proto_rawDescGZIP(), []int{5}
}

func (x *CancionId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_serviciosCanciones_proto protoreflect.FileDescriptor

const file_serviciosCanciones_proto_rawDesc = "" +
	"\n" +
	"\x18serviciosCanciones.proto\x12\tservicios\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\x06Genero\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\"\xbc\x01\n" +
	"\aCancion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x18\n" +
	"\aartista\x18\x03 \x01(\tR\aartista\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x12\n" +
	"\x04anio\x18\x05 \x01(\x05R\x04anio\x12\x1a\n" +
	"\bduracion\x18\x06 \x01(\tR\bduracion\x12)\n" +
	"\x06genero\x18\a \x01(\v2\x11.servicios.GeneroR\x06genero\";\n" +
	"\fListaGeneros\x12+\n" +
	"\ageneros\x18\x01 \x03(\v2\x11.servicios.GeneroR\ageneros\"\x1a\n" +
	"\bGeneroId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"B\n" +
	"\x0eListaCanciones\x120\n" +
	"\tcanciones\x18\x01 \x03(\v2\x12.servicios.CancionR\tcanciones\"\x1b\n" +
	"\tCancionId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xe4\x01\n" +
	"\x10CancionesService\x12@\n" +
	"\rListarGeneros\x12\x16.google.protobuf.Empty\x1a\x17.servicios.ListaGeneros\x12J\n" +
	"\x18ListarCancionesPorGenero\x12\x13.servicios.GeneroId\x1a\x19.servicios.ListaCanciones\x12B\n" +
	"\x16ObtenerDetallesCancion\x12\x14.servicios.CancionId\x1a\x12.servicios.CancionB\x15Z\x13/serviciosCancionesb\x06proto3"

var (
	file_serviciosCanciones_proto_rawDescOnce sync.Once
	file_serviciosCanciones_proto_rawDescData []byte
)

func file_serviciosCanciones_proto_rawDescGZIP() []byte {
	file_serviciosCanciones_proto_rawDescOnce.Do(func() {
		file_serviciosCanciones_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serviciosCanciones_proto_rawDesc), len(file_serviciosCanciones_proto_rawDesc)))
	})
	return file_serviciosCanciones_proto_rawDescData
}

var file_serviciosCanciones_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_serviciosCanciones_proto_goTypes = []any{
	(*Genero)(nil),         // 0: servicios.Genero
	(*Cancion)(nil),        // 1: servicios.Cancion
	(*ListaGeneros)(nil),   // 2: servicios.ListaGeneros
	(*GeneroId)(nil),       // 3: servicios.GeneroId
	(*ListaCanciones)(nil), // 4: servicios.ListaCanciones
	(*CancionId)(nil),      // 5: servicios.CancionId
	(*emptypb.Empty)(nil),  // 6: google.protobuf.Empty
}
var file_serviciosCanciones_proto_depIdxs = []int32{
	0, // 0: servicios.Cancion.genero:type_name -> servicios.Genero
	0, // 1: servicios.ListaGeneros.generos:type_name -> servicios.Genero
	1, // 2: servicios.ListaCanciones.canciones:type_name -> servicios.Cancion
	6, // 3: servicios.CancionesService.ListarGeneros:input_type -> google.protobuf.Empty
	3, // 4: servicios.CancionesService.ListarCancionesPorGenero:input_type -> servicios.GeneroId
	5, // 5: servicios.CancionesService.ObtenerDetallesCancion:input_type -> servicios.CancionId
	2, // 6: servicios.CancionesService.ListarGeneros:output_type -> servicios.ListaGeneros
	4, // 7: servicios.CancionesService.ListarCancionesPorGenero:output_type -> servicios.ListaCanciones
	1, // 8: servicios.CancionesService.ObtenerDetallesCancion:output_type -> servicios.Cancion
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_serviciosCanciones_proto_init() }
func file_serviciosCanciones_proto_init() {
	if File_serviciosCanciones_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serviciosCanciones_proto_rawDesc), len(file_serviciosCanciones_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviciosCanciones_proto_goTypes,
		DependencyIndexes: file_serviciosCanciones_proto_depIdxs,
		MessageInfos:      file_serviciosCanciones_proto_msgTypes,
	}.Build()
	File_serviciosCanciones_proto = out.File
	file_serviciosCanciones_proto_goTypes = nil
	file_serviciosCanciones_proto_depIdxs = nil
}
